# -*- coding: utf-8 -*-
"""DEMO Amanda - binary logistic regression + sigmoid curve.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TkK9oadHOSo-WsLBBVUI4aiOdqTeDDm4
"""

table = pd.read_csv("data/polling_site_data/clean_precincts_with_polling_site.csv")
table.head()

#defining the function of the sigmoid curve 
def model (x):
  return 1/(1+np.exp(-x))
x1 = np.linspace(0,1,num=400)
y1 = model(x1)

#using the sigmoid curve to model the data points in the respective variables. In this case, we use the Black population as an example to model it against existence of polling site. X-variables is set to people the racial population density and Y-variable is the existnce of polling site. 
x = table.iloc[:,12]
y = table.iloc[:,16]
print(x)
model = LogisticRegression(solver='liblinear', random_state=0)

plt.scatter(x,y)
plt.scatter(x1,y1)
plt.title('Black Population Density & Polling Sites')
plt.xlabel('Population Density')
plt.ylabel('Odds Ratio of Polling Sites')
plt.show()