# -*- coding: utf-8 -*-
"""DEMO - binary logistic regression + log(odd)plot + regression stats.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cbkJZ1E1lBlzcGihympgMZOTIlgaeq1V
"""

#produdcing the the log(odd) plot using seaborn 
black = sns.regplot(x = df.iloc[:,12], y = df.iloc[:,16], data=df, logistic= True).set_title("Black: Log Odds Linear Graph")

#defining the variables in the log(odd) plots (in this example, I used the Black racial population as an example) 
b = df.iloc[:,12]
poll = df.iloc[:,16]

#obtaining regression statistics
model= smf.logit(formula="b~poll", data= df).fit()
model.summary()

#obtaining confidence interval, odds ratio, and z-value
model_odds = pd.DataFrame(np.exp(model.params), columns= ['OR'])
model_odds['z-value']= model.pvalues
model_odds[['2.5%', '97.5%']] = np.exp(model.conf_int())
model_odds