# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10NLi80IiKLmB0vcO9ykWhAjTRPstbCeP
"""

table = pd.read_csv("data/polling_site_data/clean_precincts_with_polling_site.csv", index_col = 0)
df = table.drop(columns=['Total','Hispanic','White','Black','Asian','Mixed','Others'])
df.head()

plt.figure(figsize = (38,16))
sns.set(font_scale = 2)
sns.heatmap(df.corr(), annot = True)
plt.title('Correlation Heatmap Between Independent Variables')
plt.savefig('heatmap.png')
plt.show()